### PR TITLE
Update MRI-JRA55-do-1-5-0, *1-4-0 after @HiroyukiTsujino

### PR DESCRIPTION
**Pull request by durack1**
Replace #112 
Replace #113 
Fix #111 

@HiroyukiTsujino can you take a look at this PR, it automates the table updates, along with adding your updated driver files. If this is all ok, then we can merge this and you're almost done!

### CODE REVIEW

**Comment by HiroyukiTsujino** [comment]
@durack1 thank you for this. This set indeed works with my data, except for a typo in a demo file that specifies the name of input file. (This is my mistake.) This is the part that is usually rewritten by a user, so it may not be necessary to correct it. Nonetheless, if this is not going to be too cumbersome for you, could you please correct it because it would be good to have here the same file as we keep in my JRA55-do repo. 
<pre>
diff --git a/demo/MRI-JMA-JRA55-do-1-5-0/runCmorAllWrite-1-5-0.py b/demo/MRI-JMA-JRA55-do-1-5-0/runCmorAllWrite-1-5-0.py
index fcc6cb8..8c7249d 100755
--- a/demo/MRI-JMA-JRA55-do-1-5-0/runCmorAllWrite-1-5-0.py
+++ b/demo/MRI-JMA-JRA55-do-1-5-0/runCmorAllWrite-1-5-0.py
@@ -797,7 +797,7 @@ inputDict['LIday'][key]['fileList'] = [
         'input_atmos/solid_runoff.2016.16Feb2019.nc',
         'input_atmos/solid_runoff.2017.16Feb2019.nc',
         'input_atmos/solid_runoff.2018.16Feb2019.nc',
-        'input_atmos/solid_runoff.2019.16Jan2010.nc',
+        'input_atmos/solid_runoff.2019.16Jan2020.nc',
         'input_atmos/solid_runoff.2020.24jul2020.nc'
         ]
 inputDict['LIday'][key]['inputVarName'] = 'licalvf'
</pre>

**Comment by durack1** [comment]
@HiroyukiTsujino that last final tweak is now in place and so I have merged this PR, over to you! And thanks for persisting with this, it's great we have these working examples for others to build from

**Comment by HiroyukiTsujino** [comment]
@durack1 thank you very much. I incorporated them to my JRA55-do repo and confirmed that we can generate latest JRA55-do with CMOR-3.6.0!

**Comment by durack1** [comment]
@HiroyukiTsujino perfect, glad we've worked out the bugs and 1.5.0 is near to completion!

**Pull request merged**
